/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/CAR Model.glb -o src/components/CarBody.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

useGLTF.preload('/assets/models/CAR Model.glb')

export function CarBody() {
  const { nodes, materials } = useGLTF('/assets/models/CAR Model.glb')
  return (
    <group scale={[0.34,0.32,0.32]} position={[0,-0.2,-0.02]} rotation-y={Math.PI}>
        <group position={[-0.001, 0.246, -0.031]} rotation={[0, 0, 0]} scale={0.005}>
            <mesh geometry={nodes.Lamborghini_Aventador_Wheel_FL.geometry} material={materials._Lamborghini_AventadorLamborghini_Aventador_BodySG} />
        </group>
        <group position={[-0.001, 0.246, -0.031]} rotation={[0, 0, 0]} scale={0.005}>
            <mesh geometry={nodes.Lamborghini_Aventador_Wheel_RL.geometry} material={materials._Lamborghini_AventadorLamborghini_Aventador_BodySG} />
        </group>
        <group position={[-0.001, 0.246, -0.031]} rotation={[0, 0, 0]} scale={0.005}>
            <mesh geometry={nodes.Lamborghini_Aventador_Wheel_FR.geometry} material={materials._Lamborghini_AventadorLamborghini_Aventador_BodySG} />
        </group>
        <group position={[-0.001, 0.246, -0.031]} rotation={[0, 0, 0]} scale={0.005}>
            <mesh geometry={nodes.Lamborghini_Aventador_Wheel_RR.geometry} material={materials._Lamborghini_AventadorLamborghini_Aventador_BodySG} />
        </group>
        <group position={[-0.001, 0.246, -0.031]} rotation={[0, 0, 0]} scale={0.005}>
            <mesh geometry={nodes.Lamborghini_Aventador_Body.geometry} material={materials._Lamborghini_AventadorLamborghini_Aventador_BodySG} />
        </group>
        <group position={[-0.001, 0.246, -0.031]} rotation={[0, 0, 0]} scale={0.005}>
            <mesh geometry={nodes.Lamborghini_Aventador_Glass.geometry} material={materials._Lamborghini_AventadorLamborghini_Aventador_GlassSG} />
        </group>
    </group>
  )
}